imports:
    - { resource: easy_admin/ }

easy_admin:
   list:
        max_results: 10
        actions:
            - { name: 'show', icon: 'search', label: '', title: 'Search' }
            - { name: 'edit', icon: 'pencil', label: '', title: 'Edit' }
   formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y à H:i'

   entities:
     Image:
       list:
         fields:
           - { property: 'image', type: 'image', base_path: '%app.path.assets/images%' }
       show:
         fields:
           - { property: 'image', type: 'image', base_path: '%app.path.assets/images%' }
       form:
         fields:
           - { property: 'imageFile', type: 'vich_image' }