vich_uploader:
  db_driver: orm
  mappings:
    image_produits:
      uri_prefix:         'assets/images/produits'
      upload_destination: '%kernel.project_dir%/public/assets/images/produits'

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true