panier:
  path: /panier
  defaults: {_controller: App\Controller\BoutiqueController::panier}

historique:
  path: /historique
  defaults: {_controller: App\Controller\BoutiqueController::historique}

civil:
  path: /commande/civil
  defaults: {_controller: App\Controller\CommanderController::index}

livraison:
  path: /commande/livraison
  defaults: {_controller: App\Controller\CommanderController::livraison}

payement:
  path: /commande/payement
  defaults: {_controller: App\Controller\CommanderController::payement}

valider:
  path: /commande/valider
  defaults: {_controller: App\Controller\CommanderController::valider}

paypal_valider:
  path: /paypal/valider
  defaults: {_controller: App\Controller\PaypalController::paypal_valider}