boutique:
  path: /
  defaults: {_controller: App\Controller\BoutiqueController::index}

produit:
    path: /produit/{idcate}
    controller: App\Controller\BoutiqueController::produit
    defaults:
      idcate: null

article:
    path: /article/{id}
    defaults: {_controller: App\Controller\BoutiqueController::article}

