easy_admin:
   entities:
       Article :
          class: App\Entity\Produit
          label: 'Articles'
          form:
              title: 'Ajouter/Editer un article'
              fields:
                  - { type: 'section', label: 'Informations principales' }
                  - { property: 'titre', label: 'Titre' }
                  - { property: 'description', label: 'Description' }
                  - { property: 'categorieProduit', label: 'Catégorie',type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Categorie' } }
                  - { property: 'prix', label: 'Prix', type: 'money', type_options: { currency: 'EUR' } }
                  - { property: 'imagePrincipale', label: 'Image Principale', type: 'App\Form\ImageType', type_options: { by_reference: false}}
                  - { property: 'images', label: 'Autres Images', type: 'collection', type_options: {entry_type: 'App\Form\ImageType', by_reference: false, required: false}}
          list:
              sort: ['id', 'DESC']
              title: "Liste des %%entity_label%%"

              fields:
                  - { property: 'titre', label: 'Titre' }
                  - { property: 'prix', label: 'Prix'}
                  - { property: 'categorieProduit.libelle', label: 'Catégorie' }
          search:
            fields: ['titre']
