boutique:
  path: /
  defaults: {_controller: App\Controller\BoutiqueController::index}

  produits:
    path: /produit/{idcate}
    defaults: {_controller: App\Controller\BoutiqueController::produit}

  article:
    path: /article/{id}
    defaults: {_controller: App\Controller\BoutiqueController::article}

