login:
  path: /login
  defaults:
    _controller: OCUserBundle:Security:login

login_check:
  path: /login_check

logout:
  path: /logout

inscription:
  path: /inscription
  defaults: {_controller: registerAction:inscription}